plugins { id 'com.android.application' }

android {
    namespace 'io.github.collapsar11.cuhkwayfinder'
    compileSdk { version = release(37) { it.minorApiLevel = 0 } }
    buildToolsVersion '36.0.0'
    defaultConfig {
        applicationId 'io.github.collapsar11.cuhkwayfinder'
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName '1.0.0'
    }
    buildFeatures { buildConfig true }
    buildTypes {
        release { minifyEnabled false; debuggable false }
        debug { applicationIdSuffix '.debug'; versionNameSuffix '-debug' }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.webkit:webkit:1.17.1'
    testImplementation 'junit:junit:4.13.2'
}
